Handle PCI domains other than domain 0.
On a system with more than one PCI domain:

$ /usr/sbin/sysinfo-snapshot.py
Sysinfo-snapshot is still in process...please wait till completed successfully
Gathering the information may take a while, especially in large networks
Your patience is appreciated
Traceback (most recent call last):
  File "/usr/sbin/sysinfo-snapshot.py", line 5979, in <module>
    main()
  File "/usr/sbin/sysinfo-snapshot.py", line 5976, in main
    execute(parsed_args)
  File "/usr/sbin/sysinfo-snapshot.py", line 5863, in execute
    generate_output()
  File "/usr/sbin/sysinfo-snapshot.py", line 5573, in generate_output
    arrange_dicts()
  File "/usr/sbin/sysinfo-snapshot.py", line 3819, in arrange_dicts
    arrange_server_commands_section()
  File "/usr/sbin/sysinfo-snapshot.py", line 3608, in arrange_server_commands_section
    add_command_if_exists(cmd)
  File "/usr/sbin/sysinfo-snapshot.py", line 2658, in add_command_if_exists
    status, result = pci_bus_handler()
  File "/usr/sbin/sysinfo-snapshot.py", line 2171, in pci_bus_handler
    path = os.readlink("/sys/bus/pci/devices/0000:" + device)
FileNotFoundError: [Errno 2] No such file or directory: '/sys/bus/pci/devices/0000:0001:01:00.0'

The hardcoding of "0000" in the device path assumes that there are no other domains. Prefixing the device path like this would not be necessary if lspci had been run with the '-D' option.